config/routes.rb
DataLoad::Application.routes.draw do
  resources :purchases
  post 'purchases/import'

  

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  def import
    str = params[:file].read.sub("\r",'')

    lines = str.split(/\n/).map { |l| l.split("\t") }
    header = lines[0].map { |attr_name| attr_name.sub(' ','_').to_sym }
    data = lines[1..-1]
    array_of_attrs = data.map { |l| Hash[header.zip(l)] }
    
    if purchases = Purchase.create(array_of_attrs)
      total_rev = purchases.map { |p| p.item_price*p.purchase_count }.reduce(:+)
      flash[:notice] = "Total revenue of uploaded purchases was #{total_rev}"
      redirect_to action: 'index'
    else
      raise 'AGH'
    end
  end

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:purchaser_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataLoad</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purchaser_name %><br>
    <%= f.text_field :purchaser_name %>
  </div>
  <div class="field">
    <%= f.label :item_description %><br>
    <%= f.text_field :item_description %>
  </div>
  <div class="field">
    <%= f.label :item_price %><br>
    <%= f.text_field :item_price %>
  </div>
  <div class="field">
    <%= f.label :purchase_count %><br>
    <%= f.number_field :purchase_count %>
  </div>
  <div class="field">
    <%= f.label :merchant_address %><br>
    <%= f.text_field :merchant_address %>
  </div>
  <div class="field">
    <%= f.label :merchant_name %><br>
    <%= f.text_field :merchant_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<% if flash[:notice] %>

    <div class="notice"><%= flash[:notice] %></div>

  <% end %>

<table>
  <thead>
    <tr>
      <th>Purchaser name</th>
      <th>Item description</th>
      <th>Item price</th>
      <th>Purchase count</th>
      <th>Merchant address</th>
      <th>Merchant name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.purchaser_name %></td>
        <td><%= purchase.item_description %></td>
        <td><%= purchase.item_price %></td>
        <td><%= purchase.purchase_count %></td>
        <td><%= purchase.merchant_address %></td>
        <td><%= purchase.merchant_name %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>
<%= form_tag({action: :import}, multipart: true) do %>
  <%= file_field_tag :file %>
  <%= submit_tag( "Import" ) %>
<% end %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purchaser name:</strong>
  <%= @purchase.purchaser_name %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @purchase.item_description %>
</p>

<p>
  <strong>Item price:</strong>
  <%= @purchase.item_price %>
</p>

<p>
  <strong>Purchase count:</strong>
  <%= @purchase.purchase_count %>
</p>

<p>
  <strong>Merchant address:</strong>
  <%= @purchase.merchant_address %>
</p>

<p>
  <strong>Merchant name:</strong>
  <%= @purchase.merchant_name %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>